# Upgrade versions:
# You can update your hooks to the latest version automatically by running: pre-commit autoupdate.
# By default, this will bring the hooks to the latest tag on the default branch.
# ---------
repos:
  # Websec hook is MANDATORY, DO NOT comment it.
  - repo: https://github.com/melisource/fury_websec-git-hooks
    rev: v2.0.0
    hooks:
      - id: pre_commit_hook
        stages: [pre-commit]
      - id: post_commit_hook
        stages: [post-commit]

  # Datasec hook is MANDATORY, DO NOT comment it.
  - repo: https://github.com/melisource/fury_datasec-git-hooks
    rev: 1.2.2
    hooks:
      - id: pre_commit_hook
        stages: [pre-commit]
        verbose: true
      - id: post_commit_hook
        stages: [post-commit]